### ISSUE TITLE
Progress bar length

### ISSUE THREAD

**Issue by adityam23** [glugmpstme/Progress-bar#1]
I decided to fix the length of the progress bar as 10 characters but the if statement ` if(((int)((i/(double)iter)*100))%10==0)` doesn't work as it should and progress bar overflows if number of coin tosses is above 100
`

**Comment by yinsain** [comment]
your loop is iterating for the number of iter, and if block is also calculating percentage and then mod for a progress value, its on the correct track, But your logic is half missing. HINT :: how do you fill the remaining **SPACE** percent of progress?
